 version: '3.9'

                services:
                db:
                    container_name: bns_mysql
                    build: /home/clients-docker/tnayin/mysql
                    volumes:
                    - my-vol_myqsl:/var/lib/mysql
                    ports:
                    - 3306:3306
                phpmyadmin:
                    container_name: bns_php_admin
                    depends_on:
                    - db
                    image: phpmyadmin
                    ports:
                    - 8080:80
                web:
                    container_name: bns_web
                    build: /home/clients-docker/tnayin/web
                    depends_on:
                    - phpmyadmin
                    volumes:
                    - my-vol_web:/var/www/html/file
                    ports:
                    - 80:80
                volumes:
                my-vol_web:
                my-vol_myqsl:
