version: '3.9'
services:
 web:
  container_name: arm_web
  restart: always
  build: /home/clients-docker/tnayin/web
  depends_on:
   - db
  volumes:
   - my-volum-web:/var/www/html
  ports:
   - 80:80
 db:
  container_name: arm_db
  restart: always
  build: /home/clients-docker/tnayin/mysql
  volumes:
   - my-volum-mysql:/var/lib/mysql
  ports:
   - 3306:3306
 adminer:
  container_name: arm_adminer
  restart: always
  image: phpmyadminer
  depends_on:
   - db
  ports:
   - 8080:80
  volumes:
   my-volum-mysql:
   my-volum-web:
